AWSTemplateFormatVersion: '2010-09-09'
Description: Create an RDS SQL database

Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: Identifier for the RDS DB instance
    Default: back-postgres-db
  DBMasterUsername:
    Type: String
    Description: Username for the master user of the RDS DB instance
    Default: postgres
  DBMasterPassword:
    Type: String
    Description: Password for the master user of the RDS DB instance
    Default: passgressQ11
    NoEcho: true  # Prevent password from being displayed during stack creation
  DBName:
    Type: String
    Description: Name of the initial database on the RDS instance
    Default: backdb
  DBInstanceClass:
    Type: String
    Description: Instance class for the RDS DB instance
    Default: db.m5.large
  DBAllocatedStorage:
    Type: Number
    Description: Allocated storage in gigabytes for the RDS DB instance
    Default: 20
  VpcId:
    Type: String
    Description: ID of the existing VPC where resources will be placed
    Default: vpc-087d790305e51b654

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the RDS DB instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432  # Assuming PostgreSQL database
          ToPort: 5432
          CidrIp: 0.0.0.0/0  # Allow access from all IP addresses. Restrict as needed.

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB instance
      SubnetIds:
        - subnet-01b77b3892d63fd28
        - subnet-070dfd4274f62e41f

  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      Engine: postgres
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp2
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups: [!Ref RDSSecurityGroup]
      PubliclyAccessible: true

Outputs:
  RDSEndpointAddress:
    Value: !GetAtt RDSDBInstance.Endpoint.Address
    Description: Endpoint address of the RDS DB instance
