AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for local API with Lambda functions

## Used to test 
Globals:
  Api:
    # enable CORS
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  getAllUsers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws/bootstrap
      Runtime: go1.x
      CodeUri: ./getAllUsers
      Events:
        ApiEvent1:
          Type: Api
          Properties:
            Path: /get-all
            Method: get

  getUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws/bootstrap
      Runtime: go1.x
      CodeUri: ./getUser
      Events:
        ApiEvent1:
          Type: Api
          Properties:
            Path: /get
            Method: post

  createUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws/bootstrap
      Runtime: go1.x
      CodeUri: ./createUser
      Events:
        ApiEvent1:
          Type: Api
          Properties:
            Path: /create
            Method: post

  deleteUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws/bootstrap
      Runtime: go1.x
      CodeUri: ./deleteUser
      Events:
        ApiEvent1:
          Type: Api
          Properties:
            Path: /delete
            Method: post

  loginUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws/bootstrap
      Runtime: go1.x
      CodeUri: ./loginUser
      Events:
        ApiEvent1:
          Type: Api
          Properties:
            Path: /login
            Method: post

  getKey:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws/bootstrap
      Runtime: go1.x
      CodeUri: ./getKey
      Events:
        ApiEvent1:
          Type: Api
          Properties:
            Path: /key
            Method: post
